#!/bin/sh

set -e

# get free memory
FREE_OUT="$(free -htm)"
USED=$(echo "$FREE_OUT" | awk '/Mem/ { print $3 }')
TOTAL=$(echo "$FREE_OUT" | awk '/Mem/ { print $2 }')
USEDSW=$(echo "$FREE_OUT" | awk '/Swap/ { print $3 }')
TOTALSW=$(echo "$FREE_OUT" | awk '/Swap/ { print $2 }')
# get processes
PROCESS=$(ps -eo user=|sort|uniq -c | awk '{ print $2, $1 }')
PROCESS_ALL=$(echo "$PROCESS"| awk '{SUM += $2} END { print SUM }')
PROCESS_ROOT=$(echo "$PROCESS"| awk '/root/ {print $2}')
PROCESS_USER=$(echo "$PROCESS"| awk '!/root/ {SUM += $2} END { print SUM }')

W="\e[0;39m"
G="\e[1;33m"

echo "
${W}system info:
$W  Uptime.: $W$(uptime -p | awk '{if ($1 != "test") printf("%s %s %s %s\n", $2, $3, $4, $5); }' | sed 's/,//g')
$W  Distro.: $W$(cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g')
$W  Kernel.: $W$(uname -sr)
$W  Proc...: $W$G$PROCESS_ROOT$W (r), $G$PROCESS_USER$W (u) | $G$PROCESS_ALL$W (t)
$W  CPU....:$W$(grep "name" /proc/cpuinfo | cut -d : -f2 | uniq | cut -f1 -d"@" | sed 's/(TM)//;s/(R)//;s/CPU//')
$W  Memory.: $G$USED$W used | $G$TOTAL$W in total$W
$W  Swap...: $G$USEDSW$W used | $G$TOTALSW$W in total$W"
