#!/bin/sh

barWidth=34
maxDiscUsage=90
clear="\e[39m\e[0m"
dim="\e[2m"
echo
echo 'HDD free:'

for mount_point in $(lsblk -l -p | awk 'NR >1 && $7 != "" && substr($7, 1, 1) == "/" && $7 !~ /docker/ { print $7 }'); do
    line=$(df -hl "${mount_point}" | tail -n1)
    usagePercent=$(echo "$line" | awk '{print $5}' | sed 's/%//')
    used=$(echo "$line" | awk '{print $3}')
    maxUse=$(echo "$line" | awk '{print $2}')
    usedBarWidth=$((usagePercent*barWidth/100))
    barContent=""

    if [ "${usagePercent}" -ge "${maxDiscUsage}" ]; then
        color="\e[31m"
    else
        color="\e[33m"
    fi

    barContent="${color}"
    for _ in $(seq 1 $usedBarWidth); do
        barContent="${barContent}|"
    done

    barContent="${barContent}${clear}${dim}"
    for _ in $(seq 1 $((barWidth-usedBarWidth))); do
        barContent="${barContent}-"
    done
    bar="[${barContent}${clear}]"

    printf "%-10s" "${mount_point}"
    printf "%+8s used out of %+5s\n" "$used" "$maxUse"
    echo "${bar}"
done

echo
