#!/bin/sh

set -e

FIFO_PATH="/tmp/.hdd-free-fifo"

barWidth=34
maxDiscUsage=90
clear="\e[39m\e[0m"
dim="\e[2m"
echo
echo 'HDD free:'

mkfifo "$FIFO_PATH"
(df -hl | awk 'substr($1, 1, 1) == "/" && substr($1, 1, 9) != "/dev/loop" { print }' > "$FIFO_PATH") &
while read -r line
do
    mount_point=$(echo "$line" | awk '{print $6}')
    usagePercent=$(echo "$line" | awk '{print $5}' | sed 's/%//')
    used=$(echo "$line" | awk '{print $3}')
    maxUse=$(echo "$line" | awk '{print $2}')
    usedBarWidth=$((usagePercent*barWidth/100))
    barContent=""

    if [ "${usagePercent}" -ge "${maxDiscUsage}" ]; then
        color="\e[31m"
    else
        color="\e[33m"
    fi

    barContent="${color}"
    for _ in $(seq 1 $usedBarWidth); do
        barContent="${barContent}|"
    done

    barContent="${barContent}${clear}${dim}"
    for _ in $(seq 1 $((barWidth-usedBarWidth))); do
        barContent="${barContent}-"
    done
    bar="[${barContent}${clear}]"

    printf "%-10s" "${mount_point}"
    printf "%+8s used out of %+5s\n" "$used" "$maxUse"
    echo "${bar}"
done < "$FIFO_PATH"
rm "$FIFO_PATH"

echo
