#!/bin/sh

export LANG='en_US.UTF-8'
# set column width
COLUMNS=4
# colors
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"
# sort services

link=$(readlink "$0")
thisdir=$(dirname "$link")

# get status of all services
out="$(sort < "$thisdir/.services" | while read -r service
do
	status="$(systemctl is-active "$service")"
	if [ "$status" = "active" ]
	then
		printf "%s,%s▲%s," "${service}" "${green}" "${undim}"
	else
		printf "%s,%s▼%s," "${service}" "${red}" "${undim}"
	fi

	nexti=$((i+1))
	# insert \n every $COLUMNS column
	if [ $((nexti % COLUMNS)) -eq 0 ]
	then
		printf "\n"
	fi
	i=$nexti
done)"

out="$out\n"

echo "services:"
echo "$out" | column -ts ',' | sed -e 's/^/  /'
