#!/bin/sh

export LANG='en_US.UTF-8'

SCRIPT_PATH=$(realpath "$0")
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

# set column width
COLUMNS=4
SERVICES_FILE="$SCRIPT_DIR/.services"
FIFO_PATH="/tmp/.services-fifo"

# colors
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"

service_up() {
	printf "${green}▲${undim},${green}%s${undim}," "${1}"
}

service_down() {
	printf "${red}▼${undim},${red}%s${undim}," "${1}"
}

out=""
mkfifo "$FIFO_PATH"
sort "$SERVICES_FILE" > "$FIFO_PATH" &
while read -r service
do
	status="$(systemctl is-active "$service")"
	if [ "$status" = "active" ]
	then
		out="${out}$(service_up "$service")"
	else
		out="${out}$(service_down "$service")"
	fi

	nexti=$((i+1))
	# insert \n every $COLUMNS column
	if [ $((nexti % COLUMNS)) -eq 0 ]
	then
		out="${out}\n"
	fi
	i=$nexti
done < "$FIFO_PATH"
rm "$FIFO_PATH"

out="$out\n"

echo "services:"
echo "$out" | column -ts ',' | sed -e 's/^/  /'
echo
